# Generated by Django 5.2 on 2025-04-29 00:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_collectioncomments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionComments',
            new_name='CollectionComment',
        ),
    ]
