# Generated by Django 5.2 on 2025-04-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_item_collectioncomment_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioncomment',
            old_name='note',
            new_name='item',
        ),
    ]
