# Generated by Django 5.2 on 2025-04-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_note_collectioncomment_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
    ]
