# Generated by Django 5.2 on 2025-05-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('create', 'Created new item'), ('view', 'Viewed item details'), ('delete', 'Deleted item')], max_length=20),
        ),
    ]
