# Generated by Django 5.2 on 2025-05-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioncomment',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
