# Generated by Django 5.2 on 2025-05-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0009_rename_created_at_collectioncomment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='items', to='categories.collection'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('create', 'Created new item'), ('view', 'Viewed item details'), ('delete', 'Deleted item'), ('add_to_collection', 'Added item to collection'), ('remove_from_collection', 'Removed item from collection')], max_length=25),
        ),
    ]
